# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xus5Hs5iuUS68zc6uGws_41Y0pAqN6F1
"""

import pandas as pd
import matplotlib.pyplot as plt


def grafico_clusters():
    df = pd.read_csv("clusters1.csv")
    plt.figure(figsize=(8,6))
    plt.scatter(df['x'], df['y'], c=df['cluster'], cmap='tab10', s=10)
    plt.scatter(df['centro_x'], df['centro_y'], c='black', marker='*', s=120, label='Centroides')
    plt.title("Visualización de Clusters (K-Means con KD-Tree)")
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.legend()
    plt.grid(True)
    plt.show()

if __name__ == "__main__":

    grafico_clusters()

def grafico_tiempo_vs_puntos():
    df = pd.read_csv("tiempos_1.csv")

    plt.figure(figsize=(8,6))

    for version in df['version'].unique():
        sub = df[df['version'] == version]
        plt.plot(sub['n_puntos'], sub['tiempo_ms'], marker='o', linewidth=2, label=version)

    plt.title("K-Means Fuerza Bruta vs KD-Tree - k = 5")
    plt.xlabel("Número de puntos (n)")
    plt.ylabel("Tiempo de ejecución (ms)")
    plt.legend(title="Versión", loc="upper left")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    grafico_tiempo_vs_puntos()

def grafico_tiempo_vs_puntos():
    df = pd.read_csv("C75.csv")

    plt.figure(figsize=(8,6))

    for version in df['version'].unique():
        sub = df[df['version'] == version]
        plt.plot(sub['n_puntos'], sub['tiempo_ms'], marker='o', linewidth=2, label=version)

    plt.title("K-Means Fuerza Bruta vs KD-Tree")
    plt.xlabel("Número de puntos (n)")
    plt.ylabel("Tiempo de ejecución (ms)")
    plt.legend(title="Versión", loc="upper left")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    grafico_tiempo_vs_puntos()

def grafico_tiempo_vs_clusters():
    df = pd.read_csv("ESTE2400.csv")

    plt.figure(figsize=(8,6))

    for version in df['version'].unique():
        sub = df[df['version'] == version]
        plt.plot(sub['n_clusters'], sub['tiempo_ms'], marker='o', linewidth=2, label=version)

    plt.title("Comparación: K-Means Fuerza Bruta vs KD-Tree")
    plt.xlabel("Número de clusters (k)")
    plt.ylabel("Tiempo de ejecución (ms)")
    plt.legend(title="Versión", loc="upper left")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":

    grafico_tiempo_vs_clusters()

"""PARA LA B"""

import pandas as pd
import matplotlib.pyplot as plt

def grafico_tiempo_vs_iteracion():
    # Leer el CSV (tolera comas y puntos y comas)
    df = pd.read_csv("B_KDTree.csv", sep=r'[,;]+', engine='python')

    # Limpiar los nombres de columnas
    df.columns = df.columns.str.strip()

    print("Columnas detectadas:", df.columns.tolist())

    plt.figure(figsize=(8,6))

    for version in df['version'].unique():
        sub = df[df['version'] == version]
        plt.plot(sub['ite'], sub['tiempo_ms'], marker='o', linewidth=2, label=version)

    plt.title("Tiempo de ejecución por iteración")
    plt.xlabel("Iteración")
    plt.ylabel("Tiempo (ms)")
    plt.legend(title="Versión", loc="upper left")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    grafico_tiempo_vs_iteracion()